on: push
name: miri
jobs:
  miri:
    name: "miri"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: test with Miri
        run: export RUSTFLAGS="-Zmiri-disable-isolation"; cargo miri test
